version: '3'
services:
  publisher:
    container_name: apiserver
    build:
      context: apiserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PS_HOST: postgres
      PS_PORT: 5432
      PS_USER: root
      PS_PASSWORD: root
      PS_NAME: postgres
      S3_BUCKET: mohasebat-alsahabieh
      S3_REGION: default
      S3_ENDPOINT: s3.ir-thr-at1.arvanstorage.ir
      S3_ACCESS_KEY: dbe17ff1-333f-4634-ad02-cb08054e8e04
      S3_SECRET_KEY: cf2a8e28beb07d3e4f9b261f943970c4dcbc51024d89b0c2ce594178adf1c775
      RB_URL: amqps://legpjmju:pX5gsesigF3Z9uScpa_nR7d5pSd3Cxk4@cow.rmq2.cloudamqp.com/legpjmju
    depends_on:
      - postgres

#  listener:
#    container_name: listener
#    build:
#      context: listener
#      dockerfile: Dockerfile
#    environment:
#      DB_HOST: pg
#      DB_PORT: 5432
#      DB_USER: root
#      DB_PASSWORD: root
#      DB_NAME: image-authenticator
#      S3_BUCKET: image-authenticator
#      S3_REGION: default
#      S3_ENDPOINT: s3.ir-thr-at1.arvanstorage.ir
#      S3_ACCESS_KEY: 1f587d9d-0f73-44b0-a244-eb65a38b9fb9
#      S3_SECRET_KEY: ea8f9014e2dba906a1e1d16ced994f0ddb567bee05386ccfb13646e58d41263d
#      RABBIT_URL: amqps://mihcucyt:XE1vceH1adMHJ1lutXATIm6PI79F7aUl@cow.rmq2.cloudamqp.com/mihcucyt
#    depends_on:
#      - pg
#      - publisher

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: image-authenticator
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: